theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme
minima:
  skin: solarized
  show_excerpts: true
author:
  name: Colin Klein
  email: cvklein@gmail.com
description: Nascent thoughts, cranky grumbling, and self-promotion.
permalink: pretty
timezone: Australia/Canberra
